name: CI
on:
  pull_request:
    branches: ['master', 'main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: xl
          email: eveg@qq.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: pnpm install
        run: pnpm install
      - name: pnpm Lint
        run: pnpm exec lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
      - name: pnpm build
        run: pnpm build
